### ISSUE TITLE
structure for the instruments?

### ISSUE THREAD

**Issue by hayesla** [sunpy/sunkit-instruments#1]
Should we have different submodules for each instrument i.e. `sunkit-instruments.goes` etc?

**Comment by Cadair** [comment]
I would vote yes as it would allow us to have different maintainers for each like we do in core.

**Comment by nabobalis** [comment]
Yeah, a subfolder per instr would be my feeling on the matter.

**Comment by DanRyanIrish** [comment]
> i.e. `sunkit-instruments.goes` etc?

Just to explicitly get this in before it goes too far, it shouldn't just be `sunkit-instruments.goes`.  The instrument is XRS.  I see three options:
* `sunkit-instruments.xrs`
* `sunkit-instruments.goes_xrs`
* `sunkit-instruments.goes.xrs`

Although it is more wordy, I prefer the latter as it leaves scope for someone to add something for one of the other GOES instruments if the want to.  In fact this points to a structure that could be used for the whole package, i.e.
* `sunkit-instruments.observatory.instrument`
and 
* `sunkit-instruments.observatory.instrument.subinstrument` (if applicable).

**Comment by hayesla** [comment]
yes I completely agree that we should be explicit with XRS! especially as there are other solar focused GOES instruments (e.g. magnetometer, proton fluxes) that could make it confusing

However on the later case - GOES is the mission and XRS is the instrument - do you ever really have instrument.subinstrument?

**Comment by nabobalis** [comment]
Mission.instrument? aka goes.xrs? Are there any cases that would break this pattern or be a bad idea?

**Comment by hayesla** [comment]
but yes I agree that it could be `goes.xrs'

**Comment by DanRyanIrish** [comment]
> yes I completely agree that we should be explicit with XRS! especially as there are other solar focused GOES instruments (e.g. magnetometer, proton fluxes) that could make it confusing
> 
> However on the later case - GOES is the mission and XRS is the instrument - do you ever really have instrument.subinstrument?

`sunkit-instrument.sdo.eve.megsa`?

**Comment by DanRyanIrish** [comment]
Tentative consensus from group telecon:
* submodules per instrument
* include observatory name in module name (```observatory_instrument```) if the instrument name alone is ambiguous or not well known.
