### ISSUE TITLE
Replace IRIS DN units with equivalencies

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunkit-instruments#10]
Write equivalencies using astropy units from counts (```u.ct```) to photons for ```iris_sji_dn_equivalency```, ```iris_fuv_dn_equivalency``` and ```iris_nuv_dn_equivalency```.
* Currently there is no DN unit (data number) in astropy so make the equivalency between counts (```u.ct```) and photons.
* The SJI equivalency should be in the ```sji_utils.py``` file while the FUV and NUV equivalencies should be in the ```sg_utils.py``` file.
* Look up astropy equivalencies to see how to write new equivalencies.
* The conversions between DN and photons via the detector gains can be found in the definition of the DN units in ```iris_tools```.
* These equivalencies should replace the IRIS units.

Open PR to IRIS branch.

**Comment by kakirastern** [comment]
I would like to start work on this soon.
