### ISSUE TITLE
Dropdown menus not working in doc navbar

### ISSUE THREAD

**Issue by dstansby** [sunpy/sunkit-instruments#101]
### Describe the bug

The navbar on https://docs.sunpy.org/projects/sunkit-instruments/en/stable/ seems to be broken - the dropdown menus don't dropdown anything, and are just plain links. 

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by nabobalis** [comment]
The theme is broken under Sphinx 6+ which causes this.
