### ISSUE TITLE
Rename iris_tools.py to utils/iris_utils.py

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunkit-instruments#9]
Rename ```iris_tools.py``` to ```utils/iris_utils.py```.
* This must be changed in the various places that ```iris_tools``` is imported throughout the package.
* Utils for ```sji``` or ```spectrograph``` will likely be needed later so they can have their own utils files (e.g. ```sji_utils.py``` and ```sg_utils.py```) in the ```utils``` directory at a later time.
* Most of the work on this issue will be trying to get the tests working.  Tests of other modules should be allowed to fail while addressing this issue.  Those tests can be fixed as part of other issues related to those modules.
* Increasing code coverage should not be a priority of any PR addressing this issue.  Just getting the existing iris tools tests working will suffice.  The iris tools functions may change later due to other addressing other issues.

Open PR to iris branch.

**Comment by kakirastern** [comment]
@DanRyanIrish I am starting to work on this issue today.
